apiVersion: v1
kind: ConfigMap
metadata:
  name: contato-api-config
data:
  ASPNETCORE_ENVIRONMENT: "k8s"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Username=techuser;Password=techpassword;Database=contatoDb;"
  HttpClients__regiaoApi: "http://regiao-api:8080/"
  HttpClients__dddApi: "http://ddd-api:8080/"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__User: "guest"
  RabbitMq__Password: "guest"
  RabbitMq__RegiaoQueue: "regiao.updated"
  RabbitMq__DddQueue: "ddd.updated"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft_AspNetCore: "Warning"
  AllowedHosts: "*"
