apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "techuser"
            - name: POSTGRES_PASSWORD
              value: "techpassword"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432          # Porta do serviço dentro do cluster
      targetPort: 5432    # Porta do container onde o Postgres está escutando
      nodePort: 30000     # Porta que será exposta no nó do Kubernetes
  type: NodePort          # Especificando que o serviço será exposto com NodePort
          
